INSERT INTO USUARIOS_LOGIN (ID_USUARIO, USUARIO, CONTRASENA) VALUES(2, 'admin', '123456');

INSERT INTO LISTA (ID_LISTA, NOMBRE, DESCRIPCION) VALUES(10, 'Prueba', 'Pruebita');
INSERT INTO CANCION (ID_CANCION, TITULO, ARTISTA, ALBUM, ANNO, GENERO) VALUES(10, 'Prueba', 'Juan', 'Viejitas', 2023, 'Merengue');
INSERT INTO LISTA_CANCION (ID_LISTA_CANCION, ID_LISTA, ID_CANCION) VALUES(10, 10, 10);
